apiVersion: v1
kind: Service
metadata:
  name: todo-list-app
  labels:
    id: C0939678       # label of the service
spec:
  type: ClusterIP
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 3000      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    id: C0939678       # Pod label that service is using to select Pods
