apiVersion: v1
kind: Service
metadata:
  name: todo-proxy-service
  labels:
    name: todo-proxy       # label of the service
spec:
  type: NodePort
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: 8080      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    app: proxy       # Pod label that service is using to select Pods
